apiVersion: apps/v1
kind: Deployment
metadata:
  name: smafly-config-service
  labels:
    app: smafly-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smafly-config-service
  template:
    metadata:
      labels:
        app: smafly-config-service
    spec:
      containers:
        - name: smafly-config-service
          image: smafly_management-smafly-config-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://smafly-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: smafly-config-service
spec:
  type: LoadBalancer
  selector:
    app: smafly-config-service
  ports:
    - port: 9999
      targetPort: 9999